# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bit-engine}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bob Potter"]
  s.date = %q{2009-11-17}
  s.description = %q{longer description of your gem}
  s.email = %q{bobby.potter@gmail.com}
  s.executables = ["bte_console", "bte_daemon", "bte_console.rb", "test_parser.rb", "daemon.rb", "single_download.rb", "test_local.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/bit-engine.rb",
     "spec/bit-engine_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bpot/bit-engine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ne-line summary of your gem}
  s.test_files = [
    "spec/torrent_view_spec.rb",
     "spec/spec_helper.rb",
     "spec/protcol_buffer_spec.rb",
     "spec/choker_spec.rb",
     "spec/torrent_data_spec.rb",
     "spec/piece_picker_spec.rb",
     "spec/torrent_manager_spec.rb",
     "spec/peer_connection_spec.rb",
     "spec/bit-engine_spec.rb",
     "spec/torrent_spec.rb",
     "spec/torrent_announce_spec.rb",
     "spec/peer_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
  end
end

